import random
import numpy as np
from sklearn.datasets import make_classification

def make_multi_input_classification(n_classes = 2, 
                                    n_informative_Xs=3, 
                                    n_weak_Xs=0,
                                    n_random_Xs=0,
                                    n_samples=1000, 
                                    n_features=500, 
                                    n_informative=100,
                                    n_redundant=0,
                                    n_repeated=0,
                                    class_sep=1.0,
                                    weak_noise_sd=0.2,
                                    seed = None):
    
    """Get a synthetic classification dataset with multiple input matrices that are either informative, weak, or random.
    
    arguments
    ---------
    n_classes: int, the number of categories represented in the data
    n_informative_Xs: int, the number of informative input matrices, each with information content specified by n_features, n_informative, n_redundant
    n_weak_Xs: int, the number of input matrices generated by degrading informative matrices with added Gausisan noise
    n_random_Xs: int, the number of input matrices generated by shuffling the feature rows of informative matrices
    n_samples: int, the number of samples  per matrix
    n_feature: int, the number of features  per matrix
    n_informative: int, the number of non-random features per matrix
    n_redundant: int, the number of co-linear features per matrix
    n_repeated: int, number of repeated features per matrix
    class_sep: float, the distance between classes in feature space
    weak_noise_sd: float, standard deviation of the Gaussian noise term used to generate weak matrices
    seed: int, seed for random number generator
    
    returns
    -------
    Xs: list, list of synthetic feature matrices
    y: ndarray(dtype=int), synthetic sample labels
    X_types: list of strings, ordered description of each synthetic matrix as 'informative', 'weak', or 'random'
    
    """
    
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)
            
    n_Xs = n_informative_Xs + n_weak_Xs + n_random_Xs
    
    X, y = make_classification(n_samples=n_samples, 
                               n_features=n_features * n_Xs,
                               n_informative=n_informative * n_Xs, 
                               n_redundant=n_redundant * n_Xs,
                               n_repeated=n_repeated * n_Xs,
                               class_sep=class_sep)
    
    # split synthetic data into separate matrices
    Xs = [X[:, i*n_features:(i+1)*n_features] for i in range(n_Xs)]
    
    # add extra gaussian noise to create weak matrices
    for i in range(n_weak_Xs):
        Xs[i] += np.random.normal(loc=0, scale=weak_noise_sd, size=(n_samples, n_features))
        
    # shuffle matrices that are neither informative or weak
    for i in range(n_weak_Xs, n_Xs - n_informative_Xs):
        np.random.shuffle(Xs[i])
        
    X_types = ['weak' for i in range(n_weak_Xs)] 
    X_types += ['random' for i in range(n_random_Xs)] 
    X_types += ['informative' for i in range(n_informative_Xs)]
    tuples = list(zip(Xs, X_types))
    random.shuffle(tuples)
    Xs, X_types = zip(*tuples)
    
    return list(Xs), y, list(X_types)